development:
  PG_USERNAME: "your_postgres_username"
  PG_PASSWORD: "your_postgres_password"

test:
  PG_PASSWORD: "your_postgres_password"

production:
  PG_USERNAME: ""
  PG_PASSWORD: ""
  PG_HOST: ""
  RAILS_MIN_THREADS: "8" # min threads per worker
  RAILS_MAX_THREADS: "16" # max threads per worker
  WEB_CONCURRENCY: "6" # worker, maximum = your core count (cpu)
  

