default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("PG_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>

development:
  <<: *default
  database: good-night-api-dev

test:
  <<: *default
  database: good-night-api-test

production:
  <<: *default
  database: good-night-api
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
